version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 10
  reviewers:
  - caglarturali
  ignore:
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.2.2
    - 4.2.3
  - dependency-name: babel-preset-gatsby
    versions:
    - 0.10.0
    - 0.12.1
    - 0.12.2
    - 1.0.0
  - dependency-name: "@types/react-autosuggest"
    versions:
    - 10.0.1
    - 10.1.2
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: bulma
    versions:
    - 0.9.1
  - dependency-name: "@types/react-helmet"
    versions:
    - 6.1.0
